"""Constants for Homelab server"""

# API Timeouts (seconds)
DEFAULT_TIMEOUT = 10
SHORT_TIMEOUT = 5
LONG_TIMEOUT = 30
SSH_TIMEOUT = 15
PING_TIMEOUT = 5
PLUG_TIMEOUT = 10

# Power control
POWER_CHECK_INTERVAL = 0.5
POWER_ON_MAX_WAIT = 120
POWER_OFF_MAX_WAIT = 60
POWER_THRESHOLD_WATTS = 5.0

# WOL retry settings
WOL_RETRY_COUNT = 3
WOL_RETRY_INTERVAL = 2

# Validation limits
MAX_NAME_LENGTH = 63
MAX_HOSTNAME_LENGTH = 253
MAX_ELECTRICITY_PRICE = 10.0

# SSE streaming
SSE_KEEPALIVE_INTERVAL = 15
