"""Constants for Homelab client"""

# API Timeouts (seconds)
DEFAULT_TIMEOUT = 10
SHORT_TIMEOUT = 5
LONG_TIMEOUT = 30
POWER_OPERATION_TIMEOUT = 180

# Status monitoring
DEFAULT_FOLLOW_INTERVAL = 5.0
MIN_FOLLOW_INTERVAL = 0.1
MAX_FOLLOW_INTERVAL = 3600.0
STATUS_FETCH_TIMEOUT = 30
INITIAL_DATA_TIMEOUT = 30

# Terminal refresh
MIN_REFRESH_INTERVAL = 0.1

# Validation limits
MAX_NAME_LENGTH = 63
MAX_HOSTNAME_LENGTH = 253
